### ISSUE TITLE
Attribute error when importing pymoten

### ISSUE THREAD

**Issue by ekintuncok** [gallantlab/pymoten#31]
Hi, 

Thanks for creating and sharing this package. I'm planning on using pymoten for a video frame analysis. I was able to successfully install it _(v0.0.3)_, but when I try to import it on PyCharm, I get the following error:

```
Traceback (most recent call last):
  File "~IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c59789fac0c8>", line 1, in <module>
    import moten
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/~/.venv/lib/python3.12/site-packages/moten/__init__.py", line 14, in <module>
    from moten import (pyramids,
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/~/.venv/lib/python3.12/site-packages/moten/io.py", line 195, in <module>
    def imagearray2luminance(uint8arr, size=None, filter=Image.ANTIALIAS, dtype=np.float64):
                                                         ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Best,
Ekin

**Comment by marklescroart** [comment]
This issue has been resolved with the latest version of the code on git, which is slightly ahead of what's available on pip. if you clone the code from this repo, change directories to the source directory you have cloned, and call `pip install .` it should resolve this issue.

**Comment by mvdoc** [comment]
Version 0.0.5 has just been pushed to pypi. So this issue should be fixed. Please re-install pymoten with `pip install -U pymoten`.
